.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - if [ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]; then
      echo 'REACT_APP_SERVER="https://chasseautresor.cs-campus.fr"' > viatrezor-front/.env;
      echo 'REACT_APP_SOCKET_URL=ws://chasseautresor.cs-campus.fr"' >> viatrezor-front/.env;
      else
      TAG="dev";
      echo 'REACT_APP_SERVER="https://chasseautresor.test.cs-campus.fr"' > viatrezor-front/.env;
      echo 'REACT_APP_SOCKET_URL=ws://chasseautresor.test.cs-campus.fr"' >> viatrezor-front/.env;
      fi;
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "robot\$${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context ${CI_PROJECT_DIR}/viatrezor-${IMAGE}
      --dockerfile Dockerfile
      --destination ${REGISTRY}/${IMAGE}:${TAG}
      --cache

build_front:
  extends: .build
  variables:
    IMAGE: front

build_back:
  extends: .build
  variables:
    IMAGE: back
